### ISSUE TITLE
Support Auto Discovery

### ISSUE THREAD

**Issue by P-Storm** [koenhendriks/ha-button-plus#24]
I was looking into the MQTT auto discovery. I found the following documentation: https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

Not sure how to implement it yet, but this is something for the future probably :)

**Comment by koenhendriks** [comment]
I've been playing with auto-discovery as well and manage to get a basic setup working.

To me it doesn't seem the correct match for the integration. The MQTT auto discovery works by publishing some data to the broker and Home Assistant will then automatically create the entities. But those entities will be created under the MQTT integrations. As the Button+ integration needs to do some manual configuration and updates to the Button+ device I need those entities within my Button+ integration domain.

The MQTT auto-discovery would make more sense to be developed within the firmware of the Button+. Then all you need to do is setup a broker and Home assistant would be able to retrieve matching entities.
