### ISSUE TITLE
retain topics for labels and top_labels

### ISSUE THREAD

**Issue by dixi83** [koenhendriks/ha-button-plus#26]
Values of the labels and top labels disappear after certain time (i guess 10 minutes). If I make the topics retain by publishing with MQTT explorer with the retian flag the value remains.

**Comment by koenhendriks** [comment]
Yeah that makes sense. Should be an easy fix as this is just 1 parameter in the `publish` method of the mqtt client.

**Comment by koenhendriks** [comment]
Still a bit confused why this happens though, AFAIK no other message gets published over the broker so why should it reset? Something in the firmware of the Button+ ?
