### ISSUE TITLE
HASS label Entity value does not match button value

### ISSUE THREAD

**Issue by IBlackI** [koenhendriks/ha-button-plus#28]
The value of the entity in Home Assistant does not match the value it is set to. 

Reproduction steps:
1. In home assistant open a label entity created by the integration.
2. Change the value of the entity.
3. The button now displays the new value.
![afbeelding](https://github.com/koenhendriks/ha-button-plus/assets/4059637/c356d1f3-31a8-4304-b3a3-077d1b7ee2a7)
4. Re open the modal of the label entity.
5. The displayed value does not match the value you just changed it to and is displayed on the button.
 ![afbeelding](https://github.com/koenhendriks/ha-button-plus/assets/4059637/4c623787-4229-4feb-9632-f44f0639b308)
The history also does not show the changed value

**Comment by koenhendriks** [comment]
Thanks for the issue @IBlackI , I managed to duplicate this and will try to fix it :)
