### ISSUE TITLE
When removing the integration device and entity registry remain

### ISSUE THREAD

**Issue by koenhendriks** [koenhendriks/ha-button-plus#31]
When the integration gets removed from home assistant it keeps 'dirty' configuration from the devices and entities behind. This should be cleaned up.

This should be looked into using the `async_unload_entry` in the main `__init__.py` of the integration.

**Comment by P-Storm** [comment]
I noticed that it only happens with the `via_device`, and not the base device. I couldn't find a solution, and the people who responded on the dev discord of HA couldn't spot a problem.
