### ISSUE TITLE
Weird grouping behaviour

### ISSUE THREAD

**Issue by P-Storm** [koenhendriks/ha-button-plus#48]
Reported by @nvdweem in a PR

**Describe the bug**
Grouping of the modules is weird for some users.

**To Reproduce**
1. Go to install the button+
2. Look in overview

**Expected behavior**
All modules are detached and seperate.

**Screenshots**
![ha-all-devices](https://github.com/koenhendriks/ha-button-plus/assets/830783/17c1dcaa-6e30-4e74-82e9-b2121b97eb1b)

**Additional context and/or debug log.**

Requested files attached.

[benchmark-config.json](https://github.com/koenhendriks/ha-button-plus/files/14554687/benchmark-config.json)
[woonkamer-config.json](https://github.com/koenhendriks/ha-button-plus/files/14554688/woonkamer-config.json)
[slaapkamer-config.json](https://github.com/koenhendriks/ha-button-plus/files/14554689/slaapkamer-config.json)

_Originally posted by @nvdweem in https://github.com/koenhendriks/ha-button-plus/issues/46#issuecomment-1987743667_

**Comment by P-Storm** [comment]
Looks like a weird thing happening in the `/info/connectors ` part of the json.

Slaapkamer config
```json
{
    "connectors":
    [
        {
            "id": 0,
            "type": 0
        },
        {
            "id": 1,
            "type": 2
        },
        {
            "id": 2,
            "type": 1
        },
        {
            "id": 3,
            "type": 1
        }
    ]
}
```

This is causing some troubles, currently setting this up that it won't mix and break things (and have a display 2 and 3). Will see when I can work on it, will be somewhere next week I think

**Comment by nvdweem** [comment]
Perhaps a silly question, but what makes this weird?

I have no knowledge about the structure, but seeing that I have 1 display and 2 bars I would expect this to mean that the backplate top slot is empty (or connected to the display middle connector which could be a dummy connector), the second slot has the display and the bottom 2 slots are bars.

**Comment by P-Storm** [comment]
Normally the iteration is going from bottom to top. Now in the code there are some assumptions happening about `id / 2 = bar value` for example. I did the same, and with my change of the luminescence I introduced a bug. The grouping part I still am searching for, but not enough time to research it yet.

**Comment by nvdweem** [comment]
From what I can tell, the configuration for my device behaves as I described:

```
Bar, Display
"connectors": [
	{ "id": 0, "type": 1 },
	{ "id": 1, "type": 0 },
	{ "id": 2, "type": 0 },
	{ "id": 3, "type": 2 } 
],

Bar, empty, emtpy, Bar
"connectors": [
	{ "id": 0, "type": 1 },
	{ "id": 1, "type": 0 },
	{ "id": 2, "type": 0 },
	{ "id": 3, "type": 1 }
],

Display (bottom connector in top slot), empty, emtpy, bar
"connectors": [
	{ "id": 0, "type": 2 },
	{ "id": 1, "type": 0 },
	{ "id": 2, "type": 0 },
	{ "id": 3, "type": 1 }
],

empty, empty, display (so display bottom connector does not connect)
"connectors": [],
```
The last one was to confirm that the only interesting connector for the display is the bottom one.
