### ISSUE TITLE
Add linter and/or basic Python validator as Action

### ISSUE THREAD

**Issue by koenhendriks** [koenhendriks/ha-button-plus#53]
Should add some basic linter as a GH Action to have PRs checked.
 https://github.com/koenhendriks/ha-button-plus/issues/50#issuecomment-2017364001_

**Comment by P-Storm** [comment]
Noticed that we have to look into the error of `Use lazy % formatting in logging functions`. This is for performance reasons.

So not only the basic linter, but also fixing those warning/info problems I would say.

**Comment by koenhendriks** [comment]
Should be fixed with #59 and #58
