### ISSUE TITLE
ButtonPlusBrightness is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by roodbaard80** [koenhendriks/ha-button-plus#56]
After upgrading the HA integration from version 0.9 to 0.12 I get this warning in the HA log:

Logger: homeassistant.components.number
Source: components/number/__init__.py:216
integration: Number (documentation, issues)
First occurred: 10:34:27 (1 occurrences)
Last logged: 10:34:27

custom_components.button_plus.number::ButtonPlusBrightness is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author

**Comment by wimjanse** [comment]
Same for me with v0.12

**Comment by P-Storm** [comment]
In 0.9 we introduced the brightness component that is using this. I didn't looked into how to fix this deprecated function, but thanks for the report :+1:
