### ISSUE TITLE
entities are not linked to devices after upgrade to 0.12

### ISSUE THREAD

**Issue by roodbaard80** [koenhendriks/ha-button-plus#57]
I still see 5 devices and 26 entities after the upgrade, and the entities still work (button press, etc.)
But the entities no longer seem to be linked to the devices.
See the screenshot of my bar module 1 below.

I have a button with display and 3 bar modules.
Firmware 1.11

![image](https://github.com/koenhendriks/ha-button-plus/assets/59579169/49e07e3f-02ca-4922-8b05-84c99bed5c75)

![image](https://github.com/koenhendriks/ha-button-plus/assets/59579169/0bc6e2f9-dd8e-488e-b28c-aa1e5dce6f6b)

**Comment by koenhendriks** [comment]
Is this after deleting and re-adding the devices and entities (and/or the integration)?

**Comment by roodbaard80** [comment]
I have not deleted the Hub or any of the devices. I only upgrade the HA integration.
Should I delete the Hub and re-add it? Would that not mess up all my Automations? Or does the Hub (and devices/entities) get the exact same name if I re-add it?

**Comment by wimjanse** [comment]
@roodbaard80 for info, when you delete all devices from the integration, then upgrade to v0.12 and re-add the the devices, the devices/entities get exact same names.

I just updated to v0.12, no issues with my integrations.

**Comment by roodbaard80** [comment]
I think this was caused by myself: I renamed the Button plus device, causing it to lose link with HA.
I removed everything, gave the Button+ a reset and started from scratch. Works perfect now, so feel free to close this.
