### ISSUE TITLE
Menu descriptions empty when adding button+ integration

### ISSUE THREAD

**Issue by balk77** [koenhendriks/ha-button-plus#6]
Wanneer ik de integratie toevoeg zie ik dit:
<img width="415" alt="image" src="https://github.com/koenhendriks/ha-button-plus/assets/10166350/2a61820d-04ce-41dc-90c1-cd86bb0bcf43">
Ik heb de hele folder onder `custom_components` gezet

**Comment by koenhendriks** [comment]
Currently the integration no longer supports virtual devices. It will only check for devices from the website that have an IP or if the IP has been added manually. 

Also, the current repository structure is not really correct for the integration to be easily and correctly loaded. I think checking out the main branch and putting it in `custom_components/button_plus` should suffice.

**Comment by koenhendriks** [comment]
Closing as this is no longer relevant. Use HACS to install this integration.
