### ISSUE TITLE
Can´t add button again after 1.12.2 firmware update

### ISSUE THREAD

**Issue by joergkrainer** [koenhendriks/ha-button-plus#61]
After the update i manually enter Button+ device IP address to integrate button+ device but "Failed to connect, see log for more info" occours. Log:

Logger: custom_components.button_plus.config_flow
Quelle: custom_components/button_plus/config_flow.py:120
Integration: Button+ ([Dokumentation](https://github.com/koenhendriks/ha-button-plus), [Probleme](https://github.com/koenhendriks/ha-button-plus/issues))
Erstmals aufgetreten: 11:06:19 (5 Vorkommnisse)
Zuletzt protokolliert: 11:12:03

button_plus Exception in login : 'brightnesslargedisplay' - traceback: Traceback (most recent call last): File "/config/custom_components/button_plus/config_flow.py", line 95, in async_step_manual device_config: DeviceConfiguration = DeviceConfiguration.from_json( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/button_plus/button_plus_api/model.py", line 262, in from_json core=Core.from_dict(data["core"]), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/button_plus/button_plus_api/model.py", line 114, in from_dict brightness_large_display=data["brightnesslargedisplay"], ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'brightnesslargedisplay'

**Comment by balk77** [comment]
@joergkrainer I was wondering how you solved this issue?
